### ISSUE TITLE
rpmalloc crashs

### ISSUE THREAD

**Issue by migra-leutek** [rampantpixels/rpmalloc#70]
I created a dll for windows which contains rpmalloc.c and exports the rpmalloc functions.
The global operators new and delete were overwritten and contains the following code:

//********************************************************
void * operator new(size_t size)
{
 return rpmalloc(size);
}

//********************************************************
void operator delete(void * const p) noexcept
{
 rpfree(p);
}

//********************************************************
void * operator new[](size_t size)
{
 return rpmalloc(size);
}

//********************************************************
void operator delete[](void * const p)
{
 rpfree(p);
}

When I start our application it runs for about 10s and then crashes.
I attached a picture which shows the crash and the content of the variables in rpmalloc.

![rpmalloc_crash](https://user-images.githubusercontent.com/39116563/39802153-96e53224-536d-11e8-8cf3-bb5b6feef972.png)

**Comment by MJansson** [comment]
Using a custom memory allocator with DLLs in Windows is tricky, you have to make sure all allocations are routed to the correct allocator.

For example, calling a function in foo.dll which allocates memory internally (probably using the C/C++ runtime) and passing this pointer to another module which deallocates it using rpmalloc will cause this crash, since rpmalloc will assume the pointer passed to `rpfree` is a valid memory segment which was allocated by a call to `rpmalloc`.

Either you have to make sure all allocations are handled by rpmalloc (which will probably be impossible unless you can recompile all third party DLLs used, or runtime patch the symbol table in all loaded modules), or that you never pass a pointer to `rpfree` which was not allocated by `rpmalloc`
